export const allCourses = [
  {
    id: 1,
    courseName: "Durga Puja- Navaratri",
    duration: "10 Hours",
    trainerName: "Rajeev Ranjan",
    rating: "4",
    description:
      "Durga Puja is a vibrant Hindu festival celebrated mainly in the Indian subcontinent, particularly in the eastern states of India like West Bengal, Assam, and Tripura. It honors the goddess Durga, symbolizing the triumph of good over evil. The festival typically spans over nine days, culminating in the celebration of Vijayadashami, marking the victory of Durga over the demon Mahishasura. During Durga Puja, beautifully crafted idols of the goddess Durga, along with her children, are worshipped in elaborately decorated pandals (temporary structures). The festival is a time of joy, feasting, cultural events, and community gatherings, with people of all ages participating in the festivities.",
    Language: "english",
    caption: false,
    lectures: 122,
    certificate: false,
    cnntent: "",
    price: 570,
    image: "/img/course1.jpg",
    culture: "Bengali",
    pujaType: "Durga Puja",
  },
  {
    id: 2,
    courseName: "saraswati Puja",
    duration: "10 Hours",
    trainerName: "Jayanta Barman",
    rating: "4.7",
    description:
      "Durga Puja is a vibrant Hindu festival celebrated mainly in the Indian subcontinent, particularly in the eastern states of India like West Bengal, Assam, and Tripura. It honors the goddess Durga, symbolizing the triumph of good over evil. The festival typically spans over nine days, culminating in the celebration of Vijayadashami, marking the victory of Durga over the demon Mahishasura. During Durga Puja, beautifully crafted idols of the goddess Durga, along with her children, are worshipped in elaborately decorated pandals (temporary structures). The festival is a time of joy, feasting, cultural events, and community gatherings, with people of all ages participating in the festivities.",
    Language: "english",
    caption: false,
    lectures: 242,
    certificate: false,
    cnntent: "",
    price: 520,
    image: "/img/course2.gif",
  },
  {
    id: 3,
    courseName: "Durga Puja- Navaratri",
    duration: "10 Hours",
    trainerName: "Rajeev Ranjan",
    rating: "4",
    description:
      "Durga Puja is a vibrant Hindu festival celebrated mainly in the Indian subcontinent, particularly in the eastern states of India like West Bengal, Assam, and Tripura. It honors the goddess Durga, symbolizing the triumph of good over evil. The festival typically spans over nine days, culminating in the celebration of Vijayadashami, marking the victory of Durga over the demon Mahishasura. During Durga Puja, beautifully crafted idols of the goddess Durga, along with her children, are worshipped in elaborately decorated pandals (temporary structures). The festival is a time of joy, feasting, cultural events, and community gatherings, with people of all ages participating in the festivities.",
    Language: "english",
    caption: false,
    lectures: 122,
    certificate: false,
    cnntent: "",
    price: 570,
    image: "/img/course1.jpg",
    culture: "Bengali",
    pujaType: "Durga Puja",
  },
  {
    id: 4,
    courseName: "saraswati Puja",
    duration: "10 Hours",
    trainerName: "Jayanta Barman",
    rating: "4.7",
    description:
      "Durga Puja is a vibrant Hindu festival celebrated mainly in the Indian subcontinent, particularly in the eastern states of India like West Bengal, Assam, and Tripura. It honors the goddess Durga, symbolizing the triumph of good over evil. The festival typically spans over nine days, culminating in the celebration of Vijayadashami, marking the victory of Durga over the demon Mahishasura. During Durga Puja, beautifully crafted idols of the goddess Durga, along with her children, are worshipped in elaborately decorated pandals (temporary structures). The festival is a time of joy, feasting, cultural events, and community gatherings, with people of all ages participating in the festivities.",
    Language: "english",
    caption: false,
    lectures: 242,
    certificate: false,
    cnntent: "",
    price: 520,
    image: "/img/course2.gif",
  },
];

export const allPuja = [
  {
    id: 1,
    pujaName: "Saraswati",
    pujaDate: "Wed, 14 Feb, 2024",
    image: "/img/durga.jpg",
    pujaDetails:
      "Durga Puja, also known as Durgotsava, is an annual Hindu festival that celebrates the victory of the goddess Durga over the demon Mahishasura. It typically spans nine days and is observed in various parts of India,.",

    ingredient: {
      Rice: "2 kg",
      Flour: "1 kg",
      Ghee: "500 grams",
      Sugar: "1 kg",
      Jaggery: "500 grams",
      Milk: "2 liters",
    },
    summary:
      "Durga Puja, also known as Durgotsava, is an annual Hindu festival that celebrates the victory of the goddess Durga over the demon Mahishasura.",
  },
  {
    id: 2,
    pujaName: "Durga",
    image: "/img/saraswait.jpg",
    pujaDate: " 9 Oct, 2024 –  13 Oct, 2024",
    pujaDetails:
      "Durga Puja, also known as Durgotsava, is an annual Hindu festival that celebrates the victory of the goddess Durga over the demon Mahishasura. It typically spans nine days and is observed in various parts of India,.",

    ingredient: {
      Rice: "2 kg",
      Flour: "1 kg",
      Ghee: "500 grams",
      Sugar: "1 kg",
      Jaggery: "500 grams",
      Milk: "2 liters",
      Curd: "1 kg",
      Ginger: "250 grams",
      Turmeric: "100 grams",
      "Camphor (for Aarti)": "50 grams",
      "Coconut (for Aarti)": "2 pieces",
      "Milk (for Aarti)": "1 liter",
      "Flowers (for Aarti)": "2 kg",
      "Fruits (for Aarti)": "2 kg",
    },
    summary:
      "Durga Puja, also known as Durgotsava, is an annual Hindu festival that celebrates the victory of the goddess Durga over the demon Mahishasura.",
  },
  {
    id: 3,
    pujaName: "Laxmi",
    pujaDate: "Wed, 14 Feb, 2024",
    image: "/img/laxmi.webp",
    pujaDetails:
      "Durga Puja, also known as Durgotsava, is an annual Hindu festival that celebrates the victory of the goddess Durga over the demon Mahishasura. It typically spans nine days and is observed in various parts of India,.",

    ingredient: {
      Rice: "2 kg",
      Flour: "1 kg",
      Ghee: "500 grams",
      Sugar: "1 kg",
      Jaggery: "500 grams",
      Milk: "2 liters",
      Curd: "1 kg",
      Ginger: "250 grams",
      Turmeric: "100 grams",
      "Mustard Oil": "500 ml",
      Coconut: "2 pieces",
      "Fruits (Assorted)": "5 kg",
      "Nuts (Assorted)": "500 grams",
      Cardamom: "50 grams",
      Cloves: "50 grams",
      Cinnamon: "50 grams",
      "Bay Leaves": "10 pieces",
      Saffron: "2 grams",
      "Rose Water": "100 ml",
      "Sandalwood Powder": "50 grams",
      Camphor: "10 grams",
      "Betel Leaves": "50 pieces",
      "Camphor (for Aarti)": "50 grams",
      "Coconut (for Aarti)": "2 pieces",
      "Milk (for Aarti)": "1 liter",
      "Flowers (for Aarti)": "2 kg",
      "Fruits (for Aarti)": "2 kg",
    },
    summary:
      "Durga Puja, also known as Durgotsava, is an annual Hindu festival that celebrates the victory of the goddess Durga over the demon Mahishasura.",
  },
  {
    id: 4,
    pujaName: "Ganesh",
    image: "/img/ganesh.webp",
    pujaDate: " 9 Oct, 2024 –  13 Oct, 2024",
    pujaDetails:
      "Durga Puja, also known as Durgotsava, is an annual Hindu festival that celebrates the victory of the goddess Durga over the demon Mahishasura. It typically spans nine days and is observed in various parts of India,.",

    ingredient: {
      Rice: "2 kg",
      Flour: "1 kg",
      Ghee: "500 grams",
      Sugar: "1 kg",
      Jaggery: "500 grams",
      Milk: "2 liters",
      Curd: "1 kg",
      Ginger: "250 grams",
      Turmeric: "100 grams",
      "Mustard Oil": "500 ml",
      Coconut: "2 pieces",
      "Fruits (Assorted)": "5 kg",
      "Nuts (Assorted)": "500 grams",
      Cardamom: "50 grams",
      Cloves: "50 grams",
      Cinnamon: "50 grams",
      "Bay Leaves": "10 pieces",

      "Lakshmi Idol": "1 piece",
      "Saraswati Idol": "1 piece",
      Kumkum: "100 grams",
      "Turmeric Powder (for Puja)": "100 grams",
      "Roli (Red powder)": "100 grams",
      "Sandalwood Paste": "100 grams",
      "Dhoop (Incense)": "1 packet",
      "Camphor (for Aarti)": "50 grams",
      "Coconut (for Aarti)": "2 pieces",
      "Milk (for Aarti)": "1 liter",
      "Flowers (for Aarti)": "2 kg",
      "Fruits (for Aarti)": "2 kg",
    },
    summary:
      "Durga Puja, also known as Durgotsava, is an annual Hindu festival that celebrates the victory of the goddess Durga over the demon Mahishasura.",
  },
];
export const hinduPujaList = [
  "Satyanarayan",
  "Ganesh Chaturthi",
  "Navaratri",
  "Diwali",
  "Hanuman Jayanti",
  "Maha Shivaratri",
  "Krishna Janmashtami",
  "Durga",
  "Saraswati",
  "Vishwakarma",
  "Laxmi",
  "Surya",
  "Chhath",
  "Griha Pravesh",
  "Vastu",
  "Ganesh",
  "Santoshi Mata Vrat",
  "Tulsi Vivah",
  "Basant Panchami",
  "Nag Panchami",
  "Guru Purnima",
  "Pitru Paksha",
  "Karva Chauth",
  "Bhai Dooj",
  "Raksha Bandhan",
  "Kali",
  "Vat Savitri",
  "Varalakshmi Vrat",
  "Griha Shanti",
  "Havan",
  "Ganga",
  "Yamuna",
  "Narmada",
  "Saraswati",
  "Kuber",
  "Guru Nanak Jayanti",
  "Ram Navami",
  "Navagraha",
  "Dattatreya",
  "Radha Ashtami",
  "Sankranti",
  "Makar Sankranti",
  "Maha Navami",
  "Dussehra",
  "Ayudha",
  "Gowri Habba",
  "Onam",
  "Maha Ashtami",
  "Sheetala Ashtami",
  "Pitri Tarpan",
  "Hartalika Teej",
  "Gudi Padwa",
  "Pongal",
  "Thaipusam",
  "Guruvayur Ekadashi",
  "Vijaya Dashami",
  "Mahalaya",
  "Vasant Panchami",
  "Gauri",
  "Ganesha Abhishekam",
  "Shiva Abhishekam",
  "Navagraha Abhishekam",
  "Vishnu Abhishekam",
  "Kumkum Archana",
  "Chandi Homam",
  "Sudarshana Homam",
  "Lalita Sahasranama Parayanam",
  "Vishnu Sahasranama Parayanam",
  "Lakshmi Sahasranama Parayanam",
  "Saraswati Sahasranama Parayanam",
  "Sri Rudram Chamakam Parayanam",
  "Bhagavad Gita Parayanam",
  "Ayyappa",
  "Sabarimala Mandala",
  "Thiruvathira",
  "Attukal Pongala",
  "Thiruvairanikulam Temple",
  "Udayasthamana",
  "Pattabhishekam",
];

export const allPujaSamagri = [
  { id: 1, name: "Aam Pallab", image: "/img/samagri/aamPata.jpg" },
  { id: 2, name: "Bel Pata", image: "/img/samagri/belpata.webp" },

  { id: 3, name: "Green Coconut", image: "/img/samagri/coco.webp" },

  { id: 3, name: "Flower", image: "/img/samagri/flower.jpg" },

  { id: 4, name: "Towel", image: "/img/samagri/towel.jpg" },
];

export const pujaSamagriList = [
  "Puja Thala",
  "Sindoor",
  "Chandan",
  "Dhoop",
  "Agarbatti",
  "Deep",
  "Pradeep",
  "Ghee",
  "Chal",
  "Phool",
  "Darpan",
  "Dhuno",
  "Kumkum",
  "Panchamrita",
  "Betel leaves",
  "Nuts",
  "Kalash",
  "Panchpatra",
  "Janeu",
  "Ganga jal",
  "Nariyal",
  "Kumari phal",
  "Naivedya",
];
export const specialSamagriList = [
  "Bali (Sacrificial Offerings)",
  "Bael Leaves",
  "Red Cloth",
  "Black Lentils",
  "Turmeric",
  "Honey",
  "Milk",
  "Curd",
  "Sugar",
  "Rice",
  "Fruits (Banana, Apple, etc.)",
  "Flowers (Hibiscus, Marigold, etc.)",
  "Camphor",
  "Incense Sticks",
  "Sacred Thread (Mouli)",
  "Coconut",
  "Mustard Oil",
  "Red Vermilion (Roli)",
  "Chunri (Red Cloth)",
  "Bangles",
  "Bindi",
  "Kajal",
  "Perfume (Ittar)",
  "Mango Leaves",
  "Garland",
  "Tulsi Leaves",
  "Peacock Feathers",
  "Conch (Shankh)",
  "Mantra Book (Puja Vidhi)",
  "Cotton Wicks (Batti)",
];
